<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_msswbcollegegmail.com_fancybox-image</name>
   <tag></tag>
   <elementGuidId>27b16e51-6918-448d-b9d7-648e8080054a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.fancybox-image</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.fancybox-image</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>679480bf-079b-4704-884d-eb0ec9eefbf8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fancybox-image</value>
      <webElementGuid>2b139a9d-387b-4795-b45f-78a4705218f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>images/gallery/9924-3.jpg</value>
      <webElementGuid>b8c5f4b8-ad1b-40db-9f4d-047b0f84eb40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;fancybox-margin fancybox-lock&quot;]/body[@class=&quot;cms-index-index&quot;]/div[@class=&quot;fancybox-overlay fancybox-overlay-fixed&quot;]/div[@class=&quot;fancybox-wrap fancybox-desktop fancybox-type-image fancybox-opened&quot;]/div[@class=&quot;fancybox-skin&quot;]/div[@class=&quot;fancybox-outer&quot;]/div[@class=&quot;fancybox-inner&quot;]/img[@class=&quot;fancybox-image&quot;]</value>
      <webElementGuid>b1b1d18f-e2dc-474c-846d-e8610e42d4ee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/img</value>
      <webElementGuid>3c5cdd20-8e30-46e2-93a0-e4dfcc018fab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'images/gallery/9924-3.jpg']</value>
      <webElementGuid>5bb077a2-2c6c-433e-8356-5e2f47f542cd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
