<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_msswbcollegegmail.com_fancybox-image_1</name>
   <tag></tag>
   <elementGuidId>47764188-1485-4b27-8f50-8a1ff0dec954</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.fancybox-image</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.fancybox-image</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>871a287a-d252-4f6d-8689-0f7b78de5977</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fancybox-image</value>
      <webElementGuid>bd1c711a-2d8b-4816-8060-642055fffc86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>images/gallery/8895-12.jpg</value>
      <webElementGuid>b08d1c25-8edd-4583-9d0e-645becc421fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;fancybox-margin fancybox-lock&quot;]/body[@class=&quot;cms-index-index&quot;]/div[@class=&quot;fancybox-overlay fancybox-overlay-fixed&quot;]/div[@class=&quot;fancybox-wrap fancybox-desktop fancybox-type-image fancybox-opened&quot;]/div[@class=&quot;fancybox-skin&quot;]/div[@class=&quot;fancybox-outer&quot;]/div[@class=&quot;fancybox-inner&quot;]/img[@class=&quot;fancybox-image&quot;]</value>
      <webElementGuid>450e13d6-4100-49a3-aeda-a1a3dc5f30d1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/img</value>
      <webElementGuid>3c55b661-66cd-40a6-8e99-15554f012cad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'images/gallery/8895-12.jpg']</value>
      <webElementGuid>9592398c-aacd-4ce6-b51e-9b2a9b7be9c6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
