<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_PG DEGREE</name>
   <tag></tag>
   <elementGuidId>5c0be1ba-0295-490d-bccd-7295d050b36c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#product-detail-tab > li:nth-of-type(2) > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='product-detail-tab']/li[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;PG DEGREE&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a904bd0f-3680-4518-9b51-740de832599e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#pg</value>
      <webElementGuid>82ba39e0-8ab9-434d-9683-8054430de1aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>25c4a89b-d299-4583-9c0d-6804c0995760</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PG DEGREE</value>
      <webElementGuid>df5e263d-e583-4855-9db4-ef32de819a82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;product-detail-tab&quot;)/li[2]/a[1]</value>
      <webElementGuid>936936d7-739b-40e6-b2e1-1f9fe29ec103</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='product-detail-tab']/li[2]/a</value>
      <webElementGuid>6fe40a4d-be49-44f2-a6e4-4f83001105d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'PG DEGREE')]</value>
      <webElementGuid>438bc4a7-dbe9-4f9c-b88f-cc5733699881</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='UG DEGREE'])[1]/following::a[1]</value>
      <webElementGuid>afaf9e05-73e3-4036-a295-1f2e58b71339</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='COURSES OFFRED BY MSS WAKF BOARD COLLEGE'])[1]/following::a[2]</value>
      <webElementGuid>e1d836a9-36d4-41aa-8166-fa33fd38585e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='UG - SELF FINANCED'])[1]/preceding::a[1]</value>
      <webElementGuid>d4681d10-a091-4b2a-b9f8-074ecf05a69a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PG - SELF FINANCED'])[1]/preceding::a[2]</value>
      <webElementGuid>3e754de1-dcaa-49fb-a0e2-d7078a8bd0e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='PG DEGREE']/parent::*</value>
      <webElementGuid>2b622055-c8b2-4660-a950-72f790fb9ae6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#pg')]</value>
      <webElementGuid>f402d577-ec77-4bd1-9bcb-fb57b48edd8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/ul/li[2]/a</value>
      <webElementGuid>6c127d4a-77c1-4318-b3c5-86c1819a965a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#pg' and (text() = 'PG DEGREE' or . = 'PG DEGREE')]</value>
      <webElementGuid>56e8d406-1a85-4839-9a04-38e28b6a692c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
