<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_SELF-FINANCE DEPARTMENTS</name>
   <tag></tag>
   <elementGuidId>d1068317-3af4-4d41-adc2-e617804c8825</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#product-detail-tab > li:nth-of-type(2) > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='product-detail-tab']/li[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;SELF-FINANCE DEPARTMENTS&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>9c283f34-ae62-4e51-9fd1-eb61fb455875</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#self</value>
      <webElementGuid>775501ad-b9c5-49eb-8956-06a3d2b7588a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>7d613b9d-662b-4afe-8660-4239bb3cde94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SELF-FINANCE DEPARTMENTS </value>
      <webElementGuid>a08e8d5d-469e-4264-8c2d-fb41496afe33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;product-detail-tab&quot;)/li[2]/a[1]</value>
      <webElementGuid>0b0ad4f6-3510-4140-ad8e-e4c9173339d9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='product-detail-tab']/li[2]/a</value>
      <webElementGuid>0113103e-864c-4b82-960f-d3cea5cb3d07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'SELF-FINANCE DEPARTMENTS')]</value>
      <webElementGuid>9b6cba0a-e5cd-4b6c-b651-d2dd9fac4f1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='REGULAR DEPARTMENTS'])[1]/following::a[1]</value>
      <webElementGuid>91dcdae0-9941-4c2a-a94b-b50055832c4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='LIST OF DEPARTMENTS'])[1]/following::a[2]</value>
      <webElementGuid>ac83443b-6c8a-4cfc-bed7-aadf25b8759c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View Details'])[1]/preceding::a[1]</value>
      <webElementGuid>ab15b90d-1e2b-45a6-a574-a823a6df3bca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='SELF-FINANCE DEPARTMENTS']/parent::*</value>
      <webElementGuid>0ef10f78-e3a6-4cb0-ba71-9b24f623ae18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#self')]</value>
      <webElementGuid>7b5931cc-a868-4722-86c4-f830995e8bdd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/ul/li[2]/a</value>
      <webElementGuid>478a1ea9-e81f-4e17-9385-1e4ed30753b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#self' and (text() = 'SELF-FINANCE DEPARTMENTS ' or . = 'SELF-FINANCE DEPARTMENTS ')]</value>
      <webElementGuid>d3b3d245-bc69-4cd2-ae80-c34405e75c2b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
